### ISSUE TITLE
Read in Tucson Files

### ISSUE THREAD

**Issue by sajackson314314** [OpenDendro/dplPy#10]
Anushka is working on this one, this is the part of the code that reads the tucson files into the python code and saves them as temporary variables

**Comment by tyson-swetnam** [comment]
Need to push commits back to GitHub for review

**Comment by tyson-swetnam** [comment]
I have created a new branch `readers_dev` and a file `readers.py` where I am able to import the featured file types. 

We still need to fix the way that each file is parsed, and make sure that the arrays are being created as objects.

**Comment by tyson-swetnam** [comment]
We still need to get the RWL format written and working in the `readers.py` function.

**Comment by ifeoluwaale** [comment]
Added code for reading .rwl files in src/readers.py. Will improve commenting and style formatting after the entire file is complete

**Comment by tyson-swetnam** [comment]
Let's go over this during a code review (target this week 3/7) and see if we can move this to completed.

**Comment by CosiMichele** [comment]
Closed, see https://github.com/OpenDendro/dplPy/issues/5#issuecomment-1079524577.
