### ISSUE TITLE
Build 'read' for Tucson format

### ISSUE THREAD

**Issue by sajackson314314** [OpenDendro/dplPy#15]

**Comment by tyson-swetnam** [comment]
@sajackson314314 Sarah is working on the `rwl` portion of the `readers.py` script in another branch called `reader_csv_dev`. She will liaison with @anushkabande when she is ready to commit her changes back to `dev`

**Comment by CosiMichele** [comment]
@ifeoluwaale picked up where left off. Read in rwl, store in information prior to processing (readers.py > summary.py)

**Comment by CosiMichele** [comment]
Closed. See https://github.com/OpenDendro/dplPy/issues/5#issuecomment-1079524577.
