### ISSUE TITLE
Build 'read' for CSV Files

### ISSUE THREAD

**Issue by sajackson314314** [OpenDendro/dplPy#16]

**Comment by sajackson314314** [comment]
Worked on this week of 9/20

**Comment by sajackson314314** [comment]
Worked on this last week. Had a bit of trouble figuring out how to do the for loop correctly. Attached is scratchwork. ![scratchwork.PNG](https://images.zenhubusercontent.com/60ec6dc52aa90119d64dce4e/c4cff5f2-93bd-4285-aa33-0f17d9780662)

**Comment by tyson-swetnam** [comment]
@anushkabande is working on the read_csv.py in her own branch. When it is ready send me a pull request and I'll review it. Make sure the pull request sends it to `dev` and not `main`

**Comment by ifeoluwaale** [comment]
Added my code to src/readers today, with some edits to make processing the data more efficient

**Comment by CosiMichele** [comment]
@ifeoluwaale has made progress, data is stored  prior to processing (readers.py > summary.py) similar to rwl format.

**Comment by CosiMichele** [comment]
See https://github.com/OpenDendro/dplPy/issues/29#issuecomment-1058702583

**Comment by CosiMichele** [comment]
Closed. See https://github.com/OpenDendro/dplPy/issues/5#issuecomment-1079524577.
