### ISSUE TITLE
Build `detrend` for dplPy

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#26]

**Comment by CosiMichele** [comment]
Look at issue https://github.com/OpenDendro/dplPy/issues/27#issuecomment-1057476592

**Comment by CosiMichele** [comment]
See https://github.com/OpenDendro/dplPy/issues/27#issuecomment-1058708080

**Comment by CosiMichele** [comment]
See https://github.com/OpenDendro/dplPy/issues/27#issuecomment-1079523760

**Comment by CosiMichele** [comment]
Update: built and callable curves are:
- Spine
- Non-linear
- Hugershoff

Missing 2 curves. Next project will possibly regard autoregressive modeling.

**Comment by AndyBunn** [comment]
Ok. This is excellent progress. Are we (and by by “we” I mean Kevin) going to develop a testing routine to compare result between dplR and py?

—-
This device necessitates  brevity

On Apr 15, 2022, at 4:25 PM, Michele Cosi ***@***.***> wrote:

﻿

Update: built and callable curves are:

  *   Spine
  *   Non-linear
  *   Hugershoff

Missing 2 curves. Next project will possibly regard autoregressive modeling.
