### ISSUE TITLE
Build `xdate` for dplPy

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#27]

**Comment by CosiMichele** [comment]
xdate, chronology, detrend are open issues. Where can @ifeoluwaale and I find more about these? From what we have observed, we don't see them anywhere. If possible, can we be pointed to the files that output these in dplR?

**Comment by CosiMichele** [comment]
See https://github.com/OpenDendro/dplPy/issues/29#issuecomment-1058702583

Visit allowed to better understand xdate (crossdate). Will focus on reader/summary before working on xdate, chronology, detrend.

**Comment by CosiMichele** [comment]
Prior to addressing `xdate` it is necessary to tackle cubic smoothing splines. Ideally, we could use https://pypi.org/project/csaps/#description, however there are issues with installation and conflict with current `dplpy conda environment`. Will update once a method for successful installation of CSAPS is found.

**Comment by CosiMichele** [comment]
CSAPS was successfully installed and a spline function has been created. Next step is to implement such function into a detrend function (detrend will call on detrending methods such as spline).
