### ISSUE TITLE
Build 'read' for TXT Files

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#29]

**Comment by CosiMichele** [comment]
Raising issue: the text files given don't have a consistent format. It would be helpful to have additional examples. Will ask Kevin for files during lab visit (3/3/22).

**Comment by CosiMichele** [comment]
Visited Kevin's laboratory. txt files are not an issue at the moment, should focus on building reader for csv and tucson format.

**Comment by tyson-swetnam** [comment]
I'm going to move this to Icebox

**Comment by CosiMichele** [comment]
I am going to close this as right now we have no plans for txt and concentrating on rwl. Might want to reopen in the future.
