### ISSUE TITLE
Import dplR

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#4]

**Comment by tyson-swetnam** [comment]
@AndyBunn -- we need to decide if you should do a transfer of ownership of your existing `dplR` GitHub repository over to the OpenDendro organization, or if we should just Import it. 

My feeling is that the Import is the most appropriate step; but it will also likely require you to then update the CRAN Manual to reflect the changes.

https://github.com/new/import

https://github.com/AndyBunn/dplR

**Comment by AndyBunn** [comment]
Update the cran manual now? Next release? Sorry, I’m not too conversant with GH.

From: "Tyson L. Swetnam" ***@***.***>
Reply-To: OpenDendro/dplPy ***@***.***>
Date: Tuesday, July 13, 2021 at 9:31 AM
To: OpenDendro/dplPy ***@***.***>
Cc: Andy Bunn ***@***.***>, Mention ***@***.***>
Subject: Re: [OpenDendro/dplPy] Import dplR (#4)


@AndyBunn<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndyBunn&data=04%7C01%7Cbunna%40wwu.edu%7Cb0bd321fa6cb4c443bce08d9461ba635%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637617906827125517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ipm0W6y9mcyOX6g5CnCBgjqzzLR3gOOfkI2XnRYF1pQ%3D&reserved=0> -- we need to decide if you should do a transfer of ownership of your existing dplR GitHub repository over to the OpenDendro organization, or if we should just Import it.

My feeling is that the Import is the most appropriate step; but it will also likely require you to then update the CRAN Manual to reflect the changes.

https://github.com/new/import<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnew%2Fimport&data=04%7C01%7Cbunna%40wwu.edu%7Cb0bd321fa6cb4c443bce08d9461ba635%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637617906827135515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j4HqSoYzsxT7INLa%2Fzy%2FTBz96xrgWI3jlhhLJwjD8ck%3D&reserved=0>

https://github.com/AndyBunn/dplR<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndyBunn%2FdplR&data=04%7C01%7Cbunna%40wwu.edu%7Cb0bd321fa6cb4c443bce08d9461ba635%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637617906827135515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9KJtERgXb%2F8t%2BmLUYC640xtTQhJHn6Y85CHZYBHfm74%3D&reserved=0>

**Comment by tyson-swetnam** [comment]
Andy has created a static import of dplR which he can update from his main repo in the future.

The reasons are two fold: (1) CRAN depends on `andybunn/dplR` and (2) the user base expects `dplR` to be in Andy's personal space.
