### ISSUE TITLE
Check negative nyrs value in detrend to be %

### ISSUE THREAD

**Issue by AndyBunn** [OpenDendro/dplPy#72]
In version  dplPy: 0.1.2 the detrend func with -67 looks to make a 67 yr spline and not a 2/3 spline.

```
ca533 = dpl.readers("ca533.rwl")
cam161_spline67 = dpl.detrend(ca533["CAM161"], fit="spline", period=-67,method="residual", plot=True)
```
![image](https://github.com/OpenDendro/dplPy/assets/12534109/1abe821c-3879-4562-b0aa-6f6fcf8b2b84)

The 67% spline should look like this (via dplR):
![image](https://github.com/OpenDendro/dplPy/assets/12534109/b6c3d501-11c5-43f5-bab6-aae25adc5fc1)

```
library(dplR)
library(tidyverse)

#load campito
data("ca533")
yrs <- time(ca533)
CAM161 <- ca533[,"CAM161"]
mask <- is.na(CAM161)
CAM161 <- CAM161[!mask]
yrs <- yrs[!mask]
n <- length(CAM161)

# smooth it 
CAM161Sm <- caps(CAM161, nyrs = n*0.67)

ggplot() + 
  geom_line(aes(x=yrs,y=CAM161),alpha=0.6) +
  geom_line(aes(x=yrs,y=CAM161Sm),col="darkred") 
```

**Comment by ifeoluwaale** [comment]
Fixed in 0.1.3
